// This file is generated by icon spritesheet generator

export const iconNames = ['X', 'Telegram', 'Solana', 'Google', 'Github', 'Discord'] as const

export type IconName = (typeof iconNames)[number]
